project_name: hid-node

env:
  - CGO_ENABLED=1

before:
  hooks:
    - go mod tidy -compat=1.21

builds:
  - id: ubuntu-amd64
    main: ./cmd/hid-noded
    binary: hid-noded
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvm_muslc.x86_64.a -O /usr/lib/x86_64-linux-gnu/libwasmvm_muslc.a
    env:
      - CC=x86_64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=hid-node
      - -X github.com/cosmos/cosmos-sdk/version.AppName=hid-node
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,muslc,osusergo
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs -static -lm'
    tags:
      - netgo
      - muslc
      - osusergo

  - id: ubuntu-arm64
    main: ./cmd/hid-noded
    binary: hid-noded
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvm_muslc.aarch64.a -O /usr/lib/aarch64-linux-gnu/libwasmvm_muslc.a
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
    flags:
      - -mod=readonly
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=hid-node 
      - -X github.com/cosmos/cosmos-sdk/version.AppName=hid-node 
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,muslc,osusergo
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs -static -lm'
    tags:
      - netgo
      - muslc
      - osusergo

  - id: darwin-amd64
    main: ./cmd/hid-noded
    binary: hid-noded
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvmstatic_darwin.a -O /lib/libwasmvmstatic_darwin.a
    env:
      - CC=o64-clang
      - CGO_LDFLAGS=-L/lib
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -mod=readonly
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=hid-node 
      - -X github.com/cosmos/cosmos-sdk/version.AppName=hid-node 
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -linkmode=external
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,static_wasm
    tags:
      - netgo
      - static_wasm
    
archives:
  - id: release-archives
    format: tar.gz
    wrap_in_directory: true
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: hypersign-protocol
    name: hid-node
  
  draft: false
  prerelease: false
  mode: append
  header: |
    # Release Notes